---
version: '3.9'
services:
  haqq-node:
    container_name: haqq-node
    image: haqq-node:${TAG}
    environment:
    - KEY=haqq_impulse
    - CHAINID=haqq_54211-2
    - MONIKER=HaqqImpulse
    - KEYRING=test
    - KEYALGO=eth_secp256k1
    - LOGLEVEL=info    
    - CONFIG_PATH=/root/.haqqd
    ports:
    - '1317:1317'
    - '8545:8545'
    - '8546:8546'
    - '9090:9090'
    - '9091:9091'
    - '26656:26656'
    - '26657:26657'
    volumes:
    - /opt/haqq/data:/root/.haqqd
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '14gb'
    restart: unless-stopped
